title: 노순건
description: "개발 일기"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: soongun93@gmail.com
github_username: Decker-Noh
twitter_username: none
instagram_username: none
linkedin_username: none
facebook_username: none

# External API
giscus_repo: "Decker-Noh/Decker-Noh.github.io"
giscus_repoId: "R_kgDOH0Z7Aw"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOJ6fqWs4Cc7p7"
goatcounter_code: byanko77
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator
kramdown:
  input: GFM
  hard_wrap: true
